// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudyNetCore.Model.Models
{
    public partial class AuthorizationUser
    {
        public string Guid { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public DateOnly? GenerateTime { get; set; }
        public DateOnly? LoginTime { get; set; }
        public DateOnly? LastLoginTime { get; set; }
    }
}