// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudyNetCore.Model.Models
{
    public partial class AuthorizationUser
    {
        public string Guid { get; set; }
        public string Username { get; set; }
        public string Userpassword { get; set; }
        public DateOnly? Generatetime { get; set; }
        public DateOnly? Logintime { get; set; }
        public DateOnly? Lastlogintime { get; set; }
    }
}