// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudyNetCore.Model.Models
{
    public partial class AuthorizationPermission
    {
        public string Guid { get; set; }
        public string Parentid { get; set; }
        public string Permissionname { get; set; }
        public string Permissionnote { get; set; }
        public DateOnly? Generatetime { get; set; }
    }
}