// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudyNetCore.Model.Models
{
    public partial class User
    {
        public string Guid { get; set; }
        public string Username { get; set; }
        public string Userpwd { get; set; }
        public string Salt { get; set; }
    }
}